version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: krishi
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]
    depends_on: [db]

  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333"]
    volumes:
      - qdrant:/qdrant/storage

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file: [backend/.env]
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://postgres:postgres@db:5432/krishi}
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports: ["8000:8000"]
    depends_on: [db]

  web:
    build:
      context: web
    env_file: [web/.env.local]
    environment:
      KS_BACKEND: ${KS_BACKEND:-http://backend:8000}
    volumes:
      - ./web:/app
    command: npm run dev
    ports: ["3000:3000"]
    depends_on: [backend]

volumes:
  pgdata:
  qdrant:

