version: "3.9"

services:
  postgres:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant:latest
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"

  api:
    build: ./backend
    env_file: .env
    depends_on:
      - postgres
      - qdrant
    ports:
      - "8000:8000"

  web:
    build: ./web
    env_file: .env
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  pgdata:
  qdrant_data:
