version: "3.9"
services:
  api:
    build: ./backend
    container_name: ks_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
  web:
    build: ./web
    container_name: ks_web
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    depends_on:
      - api
